catalog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedListView.as_view(), name='borrowed-list'),
    path('book/<pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('books/create/', views.BookCreate.as_view(), name='book_create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from datetime import date


class Genre(models.Model):
    """Модель, представляющая жанр книги (например, научная фантастика, научно-популярная литература)."""
    name = models.CharField('Название жанра', max_length=200,
                            help_text='Введите жанр книги(Фантастика, Фентези, Детектив и т.д.)')

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

    def __str__(self):
        """Строковое отображение модели (в админ панели и т.д.)"""
        return self.name


class Language(models.Model):
    """Модель, представляющая язык (например, английский, французский, японский и т. Д.)"""
    name = models.CharField('Название языка', max_length=200,
                            help_text="Введите естественный язык книги "
                                      "(например, английский, французский, японский и т.д.)")

    class Meta:
        verbose_name = 'Язык'
        verbose_name_plural = 'Языки'

    def __str__(self):
        """Строковое отображение модели (в админ панели и т.д.)"""
        return self.name


class Book(models.Model):
    """Модель, представляющая книгу (но не конкретный экземпляр книги)."""
    title = models.CharField('Название книги', max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, verbose_name='Автор')
    summary = models.TextField('Краткое описание', max_length=1000, help_text='Введите краткое описание книги')
    isbn = models.CharField('isbn', max_length=13,
                            help_text='13-символьный '
                                      '<a href="https://www.isbn-international.org/content/what-isbn"> '
                                      'номер ISBN </a>')
    genre = models.ManyToManyField(Genre, help_text='Выберите жанр для этой книги', verbose_name='Жанры')
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, verbose_name='Язык')

    class Meta:
        verbose_name = "Книга(-у)"
        verbose_name_plural = "Книги"

    def __str__(self):
        """Строковое отображение модели (в админ панели и т.д.)"""
        return self.title

    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному экземпляру книги."""
        return reverse('book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """Модель, представляющая конкретный экземпляр книги (то есть который можно взять из библиотеки)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Уникальный идентификатор этой конкретной книги во всей библиотеке")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, verbose_name='Книга')
    imprint = models.CharField('Печатное издание', max_length=200)
    due_back = models.DateField('Дата возврата', null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Не доступна'),
        ('o', 'Выдана'),
        ('a', 'Доступна'),
        ('r', 'Зарезервирована'),
    )

    status = models.CharField('Статус', max_length=1, choices=LOAN_STATUS, blank=True,
                              default='m', help_text='Доступность книги')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Читатель')

    class Meta:
        verbose_name = "Экземпляр книги"
        verbose_name_plural = "Экземпляры книг"
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """Строковое отображение модели (в админ панели и т.д.)"""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back


class Author(models.Model):
    """Модель, представляющая автора."""
    first_name = models.CharField('Имя', max_length=100)
    last_name = models.CharField('Фамилия', max_length=100)
    date_of_birth = models.DateField('Дата рождения', null=True, blank=True)
    date_of_death = models.DateField('Дата смерти', null=True, blank=True)

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"

    def get_absolute_url(self):
        """Возвращает URL-адрес для доступа к конкретному экземпляру автора."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """Строковое отображение модели (в админ панели и т.д.)"""
        return f'{self.last_name}, { self.first_name}'

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(label='Обновить дату', help_text='Введите дату от настоящего момента до 4 недель (по умолчанию 3 недели).')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Недействительная дата - продление в прошлом'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Недействительная дата - продление более чем на 4 недели вперед'))

        return data

catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import permission_required
import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .forms import RenewBookForm
from .models import Book, BookInstance, Author, Genre


def index(request):
    """Функция отображения домашней страницы сайта."""
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits
    }

    return render(
        request,
        'index.html',
        context=context
    )


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """Функция для обновления определенного экземпляра BookInstance библиотекарем"""
    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()
            return HttpResponseRedirect(reverse('borrowed-list'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst': book_inst})


class BookListView(generic.ListView):
    """отображение списка книг"""
    model = Book
    paginate_by = 10


class BorrowedListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    paginate_by = 10
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/borrowed_list.html'
    queryset = BookInstance.objects.filter(status__exact='o').order_by('due_back')


class BookDetailView(generic.DetailView):
    """отображение детальной информации о книги"""
    model = Book


class AuthorListView(generic.ListView):
    """отображение списка авторов"""
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    """отображение детальной информации об авторе книги"""
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Общий просмотр на основе классов со списком книг, предоставленных текущему пользователю."""
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': datetime.datetime.today()}
    permission_required = 'catalog.can_mark_returned'


class AuthorUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.can_mark_returned'


class AuthorDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.can_mark_returned'


class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'


class BookUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'


class BookDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.can_mark_returned'

catalog/templates/catalog/author_confirm_delete.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Удалить автора  {{ author }}{% endblock %}

{% block content %}

<h1>Удалить автора</h1>

<p>Вы уверены, что хотите удалить автора: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да, удалить." />
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ author.last_name }}, {{ author.first_name }} {% endblock %}

{% block content %}
  <h1>Автор:  {{ author.last_name }}, {{ author.first_name }}</h1>
  <p class="text-muted">{{ author.date_of_birth }} - {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Список книг</h4>

    {% for book in author.book_set.all %}
    <hr>
    <strong><a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a></strong>
    <p>{{book.summary}}</p>
    {% endfor %}
  </div>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Добавить/обновить автора {% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Подтвердить" />

</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Список авторов {% endblock %}


{% block content %}
<h1>Список авторов</h1>

{% if author_list %}
<ul>

    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a>
        {% if perms.catalog.can_mark_returned %}
         - <a href="{% url 'author_update' author.pk %}">Изменить</a>
         - <a href="{% url 'author_delete' author.pk %}">Удалить</a>
        {% endif %}
    </li>
    {% endfor %}

</ul>
{% else %}
<p>К сожалению нет авторов в базе данных :(</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Удалить книгу  {{ book }}{% endblock %}

{% block content %}

<h1>Удалить книгу</h1>

<p>Вы уверены, что хотите удалить автора: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да, удалить." />
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ book.title }} {% endblock %}

{% block content %}
  <h1>Название: {{ book.title }}</h1>

  <p><strong>Автор:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Краткое описание:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Язык:</strong> {{ book.language }}</p>
  <p><strong>Жанр:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Копии</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Подлежит возврату:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Печатное издание:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Добавить/обновить книгу {% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Подтвердить" />

</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Список книг {% endblock %}


{% block content %}
    <h1>Список книг</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
          {% if perms.catalog.can_mark_returned %}
          - <a href="{% url 'book_update' book.pk %}">Изменить</a>
          - <a href="{% url 'book_delete' book.pk %}">Удалить</a>
          {% endif%}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>К сожалению нет книг в библиотеке :(</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Обновление {{bookinst.book.title}}{% endblock %}

{% block content %}

    <h1>Обновление: {{bookinst.book.title}}</h1>
    <p>Читатель: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Дата возврата: {{bookinst.due_back}}</p>

    <form method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Подтвердить" />
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Мои взятые книги {% endblock %}

{% block content %}
    <h1>Взятые книги</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Нет книг взаймы.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/borrowed_list.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Список заимствованных книг {% endblock %}


{% block content %}
    <h1>Список заимствованных книг</h1>

    {% if bookinstance_list %}
    <ul>

      {% for book in bookinstance_list %}
      <li class="{% if book.is_overdue %}text-danger{% endif %}">
      <a href="{{ book.book.get_absolute_url }}">{{ book.book.title }}</a> ({{book.due_back}}) - {{ book.borrower }}
          {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' book.id %}">Обновить</a>  {% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>К сожалению нет книг в библиотеке :(</p>
    {% endif %}
{% endblock %}